# Generated by Django 5.0.6 on 2024-09-16 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoDeUsoEPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Termo de Uso', 'Termo de Uso'), ('Política de Privacidade', 'Política de Privacidade')], max_length=100)),
                ('posicao', models.IntegerField(default=1)),
                ('titulo', models.CharField(blank=True, max_length=5000, null=True)),
                ('conteudo', models.TextField(default='')),
            ],
            options={
                'ordering': ['tipo', 'posicao', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(default='', max_length=200)),
                ('simbolo', models.ImageField(blank=True, null=True, upload_to='Suporte/Topico')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200)),
                ('motivo', models.CharField(blank=True, max_length=5000, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pergunta', models.CharField(max_length=5000)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suporte.topico')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=10000)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='suporte.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=2000)),
                ('conteudo', models.TextField(default='')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_topico', to='suporte.topico')),
            ],
            options={
                'ordering': ['topico', 'posicao'],
            },
        ),
    ]
