# Generated by Django 5.0.6 on 2024-09-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermoDeUsoEPrivacidade',
        ),
    ]
