# Generated by Django 5.0.6 on 2024-09-16 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('codigo_cor', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='Loja/Categorias/')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Desenvolvedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['produto'],
            },
        ),
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('codigo_cor', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='Loja/Plataformas/')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('codigo_cor', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100)),
                ('ativacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chave', to='loja.ativacao')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='Loja/Cliente/FotoPerfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False)),
                ('codigo_transacao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('preco_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagamento', models.CharField(max_length=400)),
                ('link_pagamento', models.URLField(default='', max_length=1000)),
                ('aprovado', models.BooleanField(default=False)),
                ('metodo', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento_pedido', to='loja.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_carrinho', models.BooleanField(default=False)),
                ('chave_liberada', models.BooleanField(default=False)),
                ('chave', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='loja.chave')),
                ('estoque_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='loja.estoqueproduto')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='loja.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('capa', models.ImageField(upload_to='Loja/Produtos/Capa')),
                ('trailer', models.CharField(max_length=500)),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('descricao', models.TextField(default='')),
                ('lancamento', models.DateField(default=django.utils.timezone.now)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classificacao', models.CharField(choices=[('Livre', 'Livre'), ('10 Anos', '10 Anos'), ('12 Anos', '12 Anos'), ('14 Anos', '14 Anos'), ('16 Anos', '16 Anos'), ('18 Anos', '18 Anos')], max_length=100)),
                ('quantidade_vendida', models.IntegerField(default=0)),
                ('ativacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.ativacao')),
                ('categorias', models.ManyToManyField(to='loja.categoria')),
                ('desenvolvedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.desenvolvedora')),
                ('distribuidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.distribuidora')),
                ('franquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.franquia')),
                ('gameplay', models.ManyToManyField(to='loja.gameplay')),
            ],
            options={
                'ordering': ['-tipo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='estoqueproduto',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_produto', to='loja.produto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lista_desejos',
            field=models.ManyToManyField(blank=True, to='loja.produto'),
        ),
        migrations.AddField(
            model_name='chave',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chave', to='loja.produto'),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plataforma', to='loja.plataforma')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='sistemas',
            field=models.ManyToManyField(to='loja.sistema'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.tipoproduto'),
        ),
    ]
