# Generated by Django 5.0.6 on 2024-09-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='capa',
            field=models.ImageField(upload_to='Loja/Produtos'),
        ),
    ]
